# Generated by Django 5.1 on 2024-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
